{"name": "test_case4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 5 = add(3, 2)", "trace": "def test_case4():\n>       assert 4 == add(3, 2)\nE       assert 4 == 5\nE        +  where 5 = add(3, 2)\n\ntest_use_allure.py:25: AssertionError"}, "start": 1690273914502, "stop": 1690273914502, "uuid": "1b278137-b4df-40aa-823e-20fcf53e6310", "historyId": "139885a759d1702557f4b835140fb826", "testCaseId": "f3b479c97c26db6275e7d0daa70e37eb", "fullName": "test_use_allure#test_case4", "labels": [{"name": "suite", "value": "test_use_allure"}, {"name": "host", "value": "DESKTOP-BVMI6KU"}, {"name": "thread", "value": "11496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_use_allure"}]}